# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9d737b0a545b0f9dacea6de7c58ac70ea0a6f98e6bfe2ebc0aa17dc97ddb851cacd39156efdeb5b04d83206d18fb19d96bc4e8bf8c2a75b7c8540481805474f

test:
  secret_key_base: e0909509da396e759aa6c56033a53d45cfe32d6ebfb6786da3be860005d3821e79e9290b3d8779f08c307f15c9b6f9ac6558ecec65fbc9800e4a61144cd3de56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
